from enum import Enum


class Status(str, Enum):
    SUCCEEDED = "SUCCEEDED"
    AUTH_FAILED = "AUTH_FAILED"
    ASSET_NOT_FOUND = "ASSET_NOT_FOUND"
    VOLUME_EXCEEDED = "VOLUME_EXCEEDED"
    POLICY_REJECTED = "POLICY_REJECTED"
    DRIVER_ERROR = "DRIVER_ERROR"
